[package]
name = "di-csv2xml"
version = "1.0.4"
authors = ["Markus Klein <markus.klein@blue-yonder.com>"]
license = "MIT"
publish = false
edition = "2018"

[profile.release]
lto = true

[dependencies]
quicli = "0.4.0"
csv = "1.0.5"
indicatif = "0.11.0"
strum = "0.13.0"
strum_macros = "0.13.0"
structopt = "0.2.14"

[dev-dependencies]
assert_cli = "0.6.3"
